name: Deploy latest Kepler version to Kosmos

on:
  workflow_run:
    workflows: [Publish package and Docker image]
    branches: master
    types: [completed]

env:
  DOCKER_IMAGE: "kuzzleio/kepler:latest"

jobs:
  deploy-kepler:
    name: Build Kepler Docker image
    runs-on: ubuntu-18.04
    environment: Kosmos
    steps:
      - uses: actions/checkout@v2
      - name: Install SCW CLI
        run: |
          sudo curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.4.0/scw-2.4.0-linux-x86_64"
          sudo chmod +x /usr/local/bin/scw
      - name: Fetch the Kubeconfig file
        run: scw k8s kubeconfig get ${{ secrets.KAPSULE_ID }} > kubeconfig.yml
        env:
          KAPSULE_ID: ${{ secrets.KAPSULE_ID }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
          SCW_DEFAULT_ZONE: ${{ secrets.SCW_DEFAULT_ZONE }}
      - name: Test get node
        run: |
          KUBECONFIG=kubeconfig.yaml kubectl get node
      