name: Publish package and Docker image

on:
  workflow_run:
    workflows: [Tests]
    branches: master
    types: [completed]

env:
  DOCKER_IMAGE: "kuzzleio/kepler:latest"

jobs:
  deploy-kepler:
    name: Build Kepler Docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          file: kepler/Dockerfile
          context: kepler